from typing import Protocol

from jotter.domain.entities.note import Note


class NoteRepository(Protocol):
    """Repository interface for Note entities."""

    def add(self, body: str, tag: str, added_at: str) -> Note: ...

    def get(self, note_id: int) -> Note: ...

    def list_notes(self, include_closed: bool = False, tag: str = "") -> list[Note]: ...

    def set_done(self, note_id: int, done: bool, closed_at: str | None) -> None: ...

    def edit(self, note_id: int, body: str, tag: str | None) -> None: ...

    def remove(self, note_id: int) -> None: ...

    def purge(self) -> int: ...

    def search(self, query: str, include_closed: bool = False) -> list[Note]: ...
